apiVersion : apps/v1
kind : Deployment
metadata:
  name : my-web-api-deployment  
spec : 
  replicas : 3
  selector :
    matchLabels:
      app: my-web-api-deployment
  template : 
    metadata : 
      labels:
        app : my-web-api-deployment
    spec :
      containers :
      - name : my-web-api-deployment
        image : talktoamitdhir/kubernetes:linux
        env :
          - name : BackgroundColor
            valueFrom :
              configMapKeyRef :
                name : my-web-api-config-map
                key  : config-map-key-header-color
        ports :
        - containerPort : 80
        resources : 
          limits:
            memory : "128M"
            cpu : "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"          

    
