apiVersion : apps/v1
kind : Deployment
metadata:
  name : my-web-api
  labels : 
    app : my-web-api
spec : 
  #replicas : 2
  selector :
    matchLabels:
      app: my-web-api
  template : 
    metadata : 
      labels:
        app : my-web-api
    spec :
      containers :
      - name : my-web-api
        image : talktoamitdhir/kubernetes:linux
        ports :
        - containerPort : 80
        resources : 
          limits:
            memory : "128M"
            cpu : "200m" 

    
